import { txtExtraction } from "./txt/txtExtraction";

export async function initReader({ fileType, file, data }) {
    let text;
    if (fileType === 'txt') {
        text = await txtExtraction(file).catch((error) => {
            console.error(error);
        });
    };
    return text;
};




// const text = `The original inhabitants of this state were tribals called Dasas. In the later period Aryans came and assimilated the tribals. Himachal Pradesh, or the region now comprising it, was included in the earliest Indian empire of Chandragupta Maurya. The great epic Mahabharata mentioned that the kings of this region participated in the Kurukshetra war between Kauravas and Pandavas. The practice of polyandry system of marriage in the Pandavas is still prevalent in some parts of Himachal. After Maurayas several dynasties like Kushans, Guptas, Kanuaj rulers etc. ruled this state. In the Muslim reign in India this state was harassed by the Muslim invaders but they could not penetrate on a permanent basis. In the Mughal regime the Rajas of the hill states made some l arrangements on their relations with Mughal kings. In the 19th century Ranjit Singh annexed/subjugated many parts of this state. In the British regime, British defeated the Gorkhas and entered into treaties with some Rajas and annexed the kingdom of others. But the basic pattern remained unchanged. After independence, thirty princely states merged and Himachal Pradesh was formed. In 1966, after reorganisation of Punjab state, some parts of old Punjab province were included in Himachal Pradesh. It became a full-fledged state in 25th January 1971

// Bihar has a very old and rich history. The name of this state has been mentioned even the old epics, Vedas, Purans. It was the main scene of activities of Buddha and 24 Tirthankars of Jains. Bihar's capital Patna, in that period known as Patliputra was the capital of famous rulers of ancient India like Maurya emperors, Imperial Guptas. Great rulers of the State before the Christian era were Bimbisar, Udayin, Chandragupta Maurya, Emperor Ashoka, Kanishka, Chandragupta, Samudragupta, Vikramaditya etc. The famous poet Kalidas lived in the reign of Gupta emperors. During the medieval period Muslim conquer this state. First Muslim ruler was Mohammed-bin-Bakhtiar Khalji. The Khaljis are followed by Tughlaks and then by Mughals. In the Mughal reign famous ruler Sher Shah Suri conquer this state and rules this state for a little period about 4 years. The tenth Guru of the Sikh community Gobind Singh, who created Khalsa and defended the people of North from Muslim rulers of Delhi was born here. After Battle of Palasey in 1757 the British ruled over the state and consolidated their position through successive battles and annexations. Bihar remained in the forefront of the struggle for India's freedom. In 1917 there was a struggle for freedom between indigo farmers and British government in north Bihar. In 1942 many of the young students of this state took part in Quit India Movement. Bihar was formed part of the Bengal Presidency till 1911. In 12th December 1911 a separate province of Bihar and Orissa was created. Bihar was made as a separate province in 1936.


// Rajasthan's history is very old and goes back to 3000 B.C. Rajasthan has always been known as the land of chivalry and the brave deeds of its warriors heroes, like Maharana Pratap are part of our historical and semi-historical collection of stories. The Chauhan dynasty dominated Rajput affairs from seventh century onwards and they became the rulers of the state from 12th century B.C. After Chauhans, the Guhilots of Mewar controlled the destiny. Besides Mewar, the other historically prominent states were Marwar, Jaipur, Bundi, Kota, Bharatpur and Alwar. All these state accepted the British Treaty of Subordinate Alliance in 1818 protecting the interest of princes. After the revolt of 1857, the people united themselves under the leadership of Mahatma Gandhi to contribute to the freedom movement. With the introduction of provincial autonomy in 1935 in British India, agitation for civil liberties and political rights become stronger in Rajasthan. Soon after independence, Sardar Patel began the great merger movement and in quick succession a number of unions of states, with their Rajpramukhs, were formed here. First came the Matsya Union located in Bharatpur region (1948) consisting a fraction of the states. Slowly and gradually the other states had joined the Indian Union and in 1958 the present State of Rajasthan formally came into being.
// The early history of Sikkim was not known. Its history started from 13th Century A.D., with the signing of a treaty between Lepcha Chief Thekong Tek and Tibetan prince Khye-Bhumsa at Kabi Lungtsok in North Sikkim. Later the Namgyal dynasty ruled this state for more than 300 years. This dynasty was set up by the Bhutia king Phunstog or Penchu. This dynasty also belonged the last Chogyal, Namgyal Palden Thondup. The Chogyal had developed ambitions of becoming a sovereign ruler and making Sikkim an independent state. With the march of history, events in Sikkim saw the state pass democracy and become an integral part of the Indian Union in 1975.

// The history of Jammu is quite old. It finds a mention in the epic Mahabharata. This region was ruled by Dogra rulers. Raja Maldev and Raja Ranjit Dev are the famous Dogra rulers. After Raja Ranjit Dev the Jammu's Dogra regime became weak and Maharaja Ranjit Singh of Punjab took over the state. Ranjit Singh handed over this state to one of his strongest governors and a scion of Dogra ruling family. His successors ruled the state till 1947. The Dogra King Hari Singh merged the state with the Indian Union.

// Goa was part of the powerful Maurya empire and the influence of Buddhism when Ashoka, the grandson of emperor Chandragupta ruled much of India, was felt here too. Goa, known in the bygone days as Goman Chala, Gopakapattam, Gopakapuri, Govapuri, Gomantak, etc., abounds in a rich historical heritage. Early history of Goa is obscure. In the first century of the Christian era, Goa was a part of the Satavahana Empire, followed by the Kadamba, the Rashtrakutas of Malkhed, the Chalukyas and the Silharas. The empire of the Yadavas by the end of the 14th century was displaced by the Khiljis of Delhi and thus Muslim rule came to Goa. After the discovery of the sea route to India by Vasco-da-Gama in 1498, many Portuguese expeditions came to India. In 1510, Alfonso de Albuquerque with the help of the emperor of Vijayanagar attacked and captured Goa. With the arrival of the Jesuit priest Francis Xavier in 1542 proselytisation began in Goa. However, the Portuguese continued to rule over the territory except for an interlude during the later half of the 17th century when Shivaji conquered a few areas in and around Goa. Even after India's independence, Goa continued to be in the hands of the Portuguese. However, they could not fulfill the aspirations of the Goan people and ultimately on 19 December 1961, Goa was liberated and made a composite union territory with Daman and Diu. On 30 May 1987 Goa was conferred statehood and Daman and Diu was made a separate union territory.

// `;
// The five players on each side fall into five playing positions. The tallest player is usually the center, the second-tallest and strongest is the power forward, a slightly shorter but more agile player is the small forward, and the shortest players or the best ball handlers are the shooting guard and the point guard, who implement the coach's game plan by managing the execution of offensive and defensive plays (player positioning). Informally, players may play three-on-three, two-on-two, and one-on-one.

// Invented in 1891 by Canadian-American gym teacher James Naismith in Springfield, Massachusetts, in the United States, basketball has evolved to become one of the world's most popular and widely viewed sports.[1][2] The National Basketball Association (NBA) is the most significant professional basketball league in the world in terms of popularity, salaries, talent, and level of competition[3][4] (drawing most of its talent from U.S. college basketball). Outside North America, the top clubs from national leagues qualify to continental championships such as the EuroLeague and the Basketball Champions League Americas. The FIBA Basketball World Cup and Men's Olympic Basketball Tournament are the major international events of the sport and attract top national teams from around the world. Each continent hosts regional competitions for national teams, like EuroBasket and FIBA AmeriCup.

// The FIBA Women's Basketball World Cup and Women's Olympic Basketball Tournament feature top national teams from continental championships. The main North American league is the WNBA (NCAA Women's Division I Basketball Championship is also popular), whereas the strongest European clubs participate in the EuroLeague Women.

// In December 1891, James Naismith, a Canadian-American professor of physical education and instructor at the International Young Men's Christian Association Training School (now Springfield College) in Springfield, Massachusetts,[7] was trying to keep his gym class active on a rainy day.[8] He sought a vigorous indoor game to keep his students occupied and at proper levels of fitness during the long New England winters. After rejecting other ideas as either too rough or poorly suited to walled-in gymnasiums, he invented a new game in which players would pass a ball to teammates and try to score points by tossing the ball into a basket mounted on a wall. Naismith wrote the basic rules and nailed a peach basket onto an elevated track. Naismith initially set up the peach basket with its bottom intact, which meant that the ball had to be retrieved manually after each "basket" or point scored. This quickly proved tedious, so Naismith removed the bottom of the basket to allow the balls to be poked out with a long dowel after each scored basket.

// Teams abounded throughout the 1920s. There were hundreds of men's professional basketball teams in towns and cities all over the United States, and little organization of the professional game. Players jumped from team to team and teams played in armories and smoky dance halls. Leagues came and went. Barnstorming squads such as the Original Celtics and two all-African American teams, the New York Renaissance Five ("Rens") and the (still existing) Harlem Globetrotters played up to two hundred games a year on their national tours.

// In 1946, the Basketball Association of America (BAA) was formed. The first game was played in Toronto, Ontario, Canada between the Toronto Huskies and New York Knickerbockers on November 1, 1946. Three seasons later, in 1949, the BAA merged with the National Basketball League (NBL) to form the National Basketball Association (NBA). By the 1950s, basketball had become a major college sport, thus paving the way for a growth of interest in professional basketball. In 1959, a basketball hall of fame was founded in Springfield, Massachusetts, site of the first game. Its rosters include the names of great players, coaches, referees and people who have contributed significantly to the development of the game. The hall of fame has people who have accomplished many goals in their career in basketball. An upstart organization, the American Basketball Association, emerged in 1967 and briefly threatened the NBA's dominance until the ABA-NBA merger in 1976. Today the NBA is the top professional basketball league in the world in terms of popularity, salaries, talent, and level of competition.

// FIBA (International Basketball Federation) was formed in 1932 by eight founding nations: Argentina, Czechoslovakia, Greece, Italy, Latvia, Portugal, Romania and Switzerland. At this time, the organization only oversaw amateur players. Its acronym, derived from the French Fédération Internationale de Basket-ball Amateur, was thus "FIBA". Men's basketball was first included at the Berlin 1936 Summer Olympics, although a demonstration tournament was held in 1904. The United States defeated Canada in the first final, played outdoors. This competition has usually been dominated by the United States, whose team has won all but three titles. The first of these came in a controversial final game in Munich in 1972 against the Soviet Union, in which the ending of the game was replayed three times until the Soviet Union finally came out on top.[34] In 1950 the first FIBA World Championship for men, now known as the FIBA Basketball World Cup, was held in Argentina. Three years later, the first FIBA World Championship for women, now known as the FIBA Women's Basketball World Cup, was held in Chile. Women's basketball was added to the Olympics in 1976, which were held in Montreal, Quebec, Canada with teams such as the Soviet Union, Brazil and Australia rivaling the American squads.


